#!/bin/bash
# ──────────────────────────────────────────────────────────────────────
# Detect USB Metro Host — Xcode "Run Script" build phase
#
# Writes MetroHost.h into $SRCROOT/BrickScan so AppDelegate.mm can find it.
# Placed in the same directory as AppDelegate.mm for reliable #include resolution.
#
# Priority:
#   1. Any en* interface with a link-local 169.254.x.x IP (USB tether)
#   2. Any en* interface with a routable LAN IP (WiFi / Ethernet)
# ──────────────────────────────────────────────────────────────────────

set -eu

OUTPUT_DIR="${SRCROOT:-$(dirname "$0")/..}/BrickScan"
HEADER="$OUTPUT_DIR/MetroHost.h"

USB_IP=""
WIFI_IP=""

# Scan all en* interfaces (USB tether can appear on any en1–en9 on Apple Silicon)
for iface in en0 en1 en2 en3 en4 en5 en6 en7 en8 en9; do
  ip=$(ifconfig "$iface" 2>/dev/null | grep "inet " | head -1 | awk '{print $2}') || continue
  [ -z "$ip" ] && continue
  case "$ip" in
    169.254.*)
      # Link-local → USB tether; prefer this
      USB_IP="$ip"
      echo "[BrickScan] Found USB link-local: $iface → $ip"
      ;;
    127.*)
      # loopback — skip
      ;;
    *)
      # Routable LAN address — use as WiFi fallback (first match wins)
      [ -z "$WIFI_IP" ] && WIFI_IP="$ip" && echo "[BrickScan] Found LAN: $iface → $ip"
      ;;
  esac
done

if [ -n "$USB_IP" ]; then
  METRO_IP="$USB_IP"
  echo "[BrickScan] Metro host: $METRO_IP (USB link-local)"
elif [ -n "$WIFI_IP" ]; then
  METRO_IP="$WIFI_IP"
  echo "[BrickScan] Metro host: $METRO_IP (WiFi/LAN)"
else
  # Last resort — hardcoded safe default
  METRO_IP="172.31.205.125"
  echo "[BrickScan] Metro host: $METRO_IP (hardcoded fallback)"
fi

# Write the header only if the IP changed (avoids unnecessary rebuilds)
NEW_CONTENT="// Auto-generated by detect_metro_host.sh — do not edit
#define METRO_USB_HOST @\"$METRO_IP\""

if [ -f "$HEADER" ]; then
  OLD_CONTENT=$(cat "$HEADER")
  if [ "$OLD_CONTENT" = "$NEW_CONTENT" ]; then
    echo "[BrickScan] MetroHost.h unchanged ($METRO_IP)"
    exit 0
  fi
fi

mkdir -p "$OUTPUT_DIR"
printf '%s' "$NEW_CONTENT" > "$HEADER"
echo "[BrickScan] Wrote MetroHost.h → $METRO_IP"
