#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTLinkingManager.h>
#include <ifaddrs.h>
#include <arpa/inet.h>
#include <net/if.h>

// MetroHost.h was previously generated by a build phase script to bake the
// USB IP at build time. That build phase has been removed — runtime detection
// in resolveMetroHost() handles all cases now. This include is kept only as
// a safety net for any leftover MetroHost.h from an old build; it is a no-op
// if the file doesn't exist.
#if __has_include("MetroHost.h")
  #import "MetroHost.h"
#endif

@implementation AppDelegate

/// Probe whether Metro is reachable at host (host or host:port) with a short timeout.
/// Constructs http://<host>/status — respects embedded port (e.g. "host:80").
+ (BOOL)isMetroReachableAt:(NSString *)host {
  // If host already contains a port, use it directly; otherwise append :8081
  NSString *urlStr;
  if ([host rangeOfString:@":"].location != NSNotFound) {
    urlStr = [NSString stringWithFormat:@"http://%@/status", host];
  } else {
    urlStr = [NSString stringWithFormat:@"http://%@:8081/status", host];
  }
  NSURL *url = [NSURL URLWithString:urlStr];
  if (!url) return NO;

  // Retry up to 2 times — USB link-local can take a moment to respond after
  // a cable reconnect. Each attempt uses a 3 s TCP timeout with a 3.5 s wall
  // clock guard, so worst-case per-candidate cost is ~7 s total.
  for (int attempt = 0; attempt < 2; attempt++) {
    if (attempt > 0) {
      [NSThread sleepForTimeInterval:1.0];   // brief pause before retry
    }

    NSMutableURLRequest *req = [NSMutableURLRequest requestWithURL:url];
    req.timeoutInterval = 3.0;             // enough for USB link-local APIPA
    req.HTTPMethod = @"HEAD";
    req.cachePolicy = NSURLRequestReloadIgnoringLocalCacheData;

    __block BOOL reachable = NO;
    dispatch_semaphore_t sem = dispatch_semaphore_create(0);

    [[[NSURLSession sharedSession] dataTaskWithRequest:req
                                     completionHandler:^(NSData *d, NSURLResponse *r, NSError *e) {
      if (!e && [(NSHTTPURLResponse *)r statusCode] < 400) reachable = YES;
      dispatch_semaphore_signal(sem);
    }] resume];

    // Guard: wait at most 3.5 s for the completion handler
    dispatch_semaphore_wait(sem, dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3.5 * NSEC_PER_SEC)));
    if (reachable) return YES;
  }
  return NO;
}

/// Collect candidate Metro host addresses to probe at runtime.
/// Includes both the iPhone's own IPs (for USB peer-reachable hosts) and
/// the point-to-point PEER addresses (the Mac's link-local USB IP).
+ (NSArray<NSString *> *)allLocalIPv4Addresses {
  NSMutableArray<NSString *> *addresses = [NSMutableArray array];
  struct ifaddrs *ifaddr = NULL;
  if (getifaddrs(&ifaddr) != 0) return addresses;

  for (struct ifaddrs *ifa = ifaddr; ifa != NULL; ifa = ifa->ifa_next) {
    if (!ifa->ifa_addr || ifa->ifa_addr->sa_family != AF_INET) continue;
    if (strcmp(ifa->ifa_name, "lo0") == 0) continue;  // skip loopback

    // Add the interface's own address
    struct sockaddr_in *sin = (struct sockaddr_in *)ifa->ifa_addr;
    char buf[INET_ADDRSTRLEN];
    if (inet_ntop(AF_INET, &sin->sin_addr, buf, sizeof(buf))) {
      [addresses addObject:[NSString stringWithUTF8String:buf]];
    }

    // For point-to-point interfaces (USB tether), also probe the PEER address.
    // ifa_dstaddr holds the remote (Mac) side of the P2P link — this is exactly
    // the address Metro is bound to on the Mac.
    if ((ifa->ifa_flags & IFF_POINTOPOINT) && ifa->ifa_dstaddr &&
        ifa->ifa_dstaddr->sa_family == AF_INET) {
      struct sockaddr_in *dst = (struct sockaddr_in *)ifa->ifa_dstaddr;
      char dbuf[INET_ADDRSTRLEN];
      if (inet_ntop(AF_INET, &dst->sin_addr, dbuf, sizeof(dbuf))) {
        NSString *peer = [NSString stringWithUTF8String:dbuf];
        if (![addresses containsObject:peer]) {
          NSLog(@"[BrickScan] Adding USB P2P peer: %s → %@", ifa->ifa_name, peer);
          [addresses addObject:peer];
        }
      }
    }
  }
  freeifaddrs(ifaddr);
  return addresses;
}

/// Probe all local IPs concurrently and return the first one where Metro answers.
+ (NSString *)scanForMetroHost {
  NSArray<NSString *> *candidates = [self allLocalIPv4Addresses];
  if (candidates.count == 0) return nil;

  NSLog(@"[BrickScan] Scanning %lu local IPs for Metro: %@", (unsigned long)candidates.count,
        [candidates componentsJoinedByString:@", "]);

  __block NSString *found = nil;
  dispatch_group_t group = dispatch_group_create();
  dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0);
  NSLock *lock = [[NSLock alloc] init];

  for (NSString *ip in candidates) {
    dispatch_group_async(group, queue, ^{
      if ([self isMetroReachableAt:ip]) {
        [lock lock];
        if (!found) {
          found = ip;
          NSLog(@"[BrickScan] Metro found via scan at %@", ip);
        }
        [lock unlock];
      }
    });
  }

  // Wait up to 8 s total: each probe retries once (3.5 s + 1 s sleep + 3.5 s),
  // but concurrent dispatch means we only pay the cost of the slowest candidate.
  dispatch_group_wait(group, dispatch_time(DISPATCH_TIME_NOW, (int64_t)(8.0 * NSEC_PER_SEC)));
  return found;
}

/// Return the best Metro host: scan all local interfaces first, then fall back
/// to build-time detection. This handles USB link-local IPs that change on
/// every cable reconnect without requiring a rebuild.
+ (NSString *)resolveMetroHost {
  // 1. Scan all live network interfaces (USB, WiFi, etc.) concurrently
  NSString *scanned = [self scanForMetroHost];
  if (scanned) return scanned;

  // 2. Try the RCTBundleURLProvider's previously saved host
  NSString *rctHost = [RCTBundleURLProvider sharedSettings].jsLocation;
  if (rctHost.length > 0 && ![rctHost isEqualToString:@"localhost"]) {
    NSLog(@"[BrickScan] Trying saved RCTBundleURLProvider host: %@", rctHost);
    if ([self isMetroReachableAt:rctHost]) {
      NSLog(@"[BrickScan] Metro found at saved host %@", rctHost);
      return rctHost;
    }
  }

  // 3. Fall back to the build-time detected IP, or localhost
#ifdef METRO_USB_HOST
  NSLog(@"[BrickScan] No Metro found via scan, using build-time host %@", METRO_USB_HOST);
  return METRO_USB_HOST;
#else
  NSLog(@"[BrickScan] No Metro found, defaulting to localhost");
  return @"localhost";
#endif
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"main";

  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
  return [self bundleURL];
}

- (NSURL *)bundleURL
{
#if DEBUG
  // Resolve the best Metro host: build-time header → WiFi → USB → localhost
  NSString *host = [AppDelegate resolveMetroHost];
  NSLog(@"[BrickScan] Using Metro host: %@", host);

  // Set jsLocation on the shared provider so HMR/fast-refresh uses the same host.
  // The packagerHost: API bypasses shared settings, breaking HMR setup.
  [RCTBundleURLProvider sharedSettings].jsLocation = host;
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@".expo/.virtual-metro-entry"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [super application:application openURL:url options:options] || [RCTLinkingManager application:application openURL:url options:options];
}

// Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  BOOL result = [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
  return [super application:application continueUserActivity:userActivity restorationHandler:restorationHandler] || result;
}

// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  return [super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
  return [super application:application didFailToRegisterForRemoteNotificationsWithError:error];
}

// Explicitly define remote notification delegates to ensure compatibility with some third-party libraries
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  return [super application:application didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

@end
